# Generated by Django 5.2.16 on 2026-08-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField(help_text="On-duty hours already used in the driver's 70hr/8-day cycle.")),
                ('start_time', models.DateTimeField()),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('truck_number', models.CharField(blank=True, max_length=60)),
                ('total_miles', models.FloatField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
